module.exports = {
  "title": "",
  "ctx": {},
  "suites": [
    {
      "title": "macaca-test/desktop-browser-sample.test.js",
      "ctx": {
        "_runnable": {
          "title": "\"after all\" hook",
          "body": "function () {\n    opn(path.join(__dirname, '..', 'reports', 'index.html'));\n  }",
          "async": 0,
          "sync": true,
          "_timeout": 300000,
          "_slow": 75,
          "_enableTimeouts": true,
          "timedOut": false,
          "_trace": {},
          "_retries": -1,
          "_currentRetry": 0,
          "pending": false,
          "type": "hook",
          "parent": "[Circular ~.suites.0]",
          "ctx": "[Circular ~.suites.0.ctx]",
          "_events": {},
          "_eventsCount": 1,
          "duration": 4,
          "_error": null
        },
        "test": {
          "title": "\"after all\" hook",
          "body": "function () {\n    opn(path.join(__dirname, '..', 'reports', 'index.html'));\n  }",
          "async": 0,
          "sync": true,
          "_timeout": 300000,
          "_slow": 75,
          "_enableTimeouts": true,
          "timedOut": false,
          "_trace": {},
          "_retries": -1,
          "_currentRetry": 0,
          "pending": false,
          "type": "hook",
          "parent": "[Circular ~.suites.0]",
          "ctx": "[Circular ~.suites.0.ctx]",
          "_events": {},
          "_eventsCount": 1,
          "duration": 4,
          "_error": null
        }
      },
      "suites": [
        {
          "title": "macaca desktop sample",
          "ctx": {
            "_runnable": {
              "title": "\"after all\" hook",
              "body": "() => {\n      return driver\n        .quit();\n    }",
              "async": 0,
              "sync": true,
              "_timeout": 300000,
              "_slow": 75,
              "_enableTimeouts": true,
              "timedOut": false,
              "_trace": {},
              "_retries": -1,
              "_currentRetry": 0,
              "pending": false,
              "type": "hook",
              "parent": "[Circular ~.suites.0.suites.0]",
              "ctx": "[Circular ~.suites.0.suites.0.ctx]",
              "_events": {},
              "_eventsCount": 1,
              "timer": {
                "0": null,
                "_called": false,
                "_idleTimeout": -1,
                "_idlePrev": null,
                "_idleNext": null,
                "_idleStart": 58337,
                "_onTimeout": null,
                "_repeat": null
              },
              "duration": 7,
              "_error": null
            },
            "test": {
              "title": "\"after all\" hook",
              "body": "() => {\n      return driver\n        .quit();\n    }",
              "async": 0,
              "sync": true,
              "_timeout": 300000,
              "_slow": 75,
              "_enableTimeouts": true,
              "timedOut": false,
              "_trace": {},
              "_retries": -1,
              "_currentRetry": 0,
              "pending": false,
              "type": "hook",
              "parent": "[Circular ~.suites.0.suites.0]",
              "ctx": "[Circular ~.suites.0.suites.0.ctx]",
              "_events": {},
              "_eventsCount": 1,
              "timer": {
                "0": null,
                "_called": false,
                "_idleTimeout": -1,
                "_idlePrev": null,
                "_idleNext": null,
                "_idleStart": 58337,
                "_onTimeout": null,
                "_repeat": null
              },
              "duration": 7,
              "_error": null
            }
          },
          "suites": [],
          "tests": [
            {
              "title": "#0 should be ok",
              "fullTitle": "macaca desktop sample--#0 should be ok",
              "duration": 7509,
              "state": "passed",
              "pass": true,
              "fail": false,
              "pending": false,
              "context": "\"../screenshots/34da7aaa-e94d-48be-a93a-70e851c952af.png\"",
              "code": "const url = path.join(__dirname, './pages/desktop-sample.html');\nreturn driver\n  .get(`file://${url}`)\n  .sleep(3000)\n  .execute(`document.querySelector('#select').selectedIndex = 1`)\n  .sleep(1000)\n  .elementById('select')\n  /*\n  .getProperty('value')\n  .then(value => {\n    value.should.be.equal('2');\n  })\n  */\n  .execute(`\n    var element = document.querySelector('#hover_text');\n    var event = document.createEvent('MouseEvent');\n    event.initMouseEvent('mouseover', true, true);\n    element.dispatchEvent(event);\n  `)\n  .elementById('hover_text')\n  .getComputedCss('color')\n  .then(value => {\n    value.should.containEql('255');\n  })\n  // https://github.com/macacajs/macaca-electron#windowalert\n  .execute(`\n    var e = document.createElement('div');\n    e.id = 'alert_msg';\n    window.alert = function() {\n      e.innerHTML = JSON.stringify(arguments[0]);\n      document.body.appendChild(e);\n    };\n  `)\n  .elementById('alert_button')\n  .click()\n  .elementById('alert_msg')\n  .text()\n  .then(value => {\n    value.should.containEql('this message is from alert');\n  })\n  .sleep(3000);",
                            "uuid": "03dacaa9-a969-4f88-bebd-5141fbe35cba",
  "skipped": false
},
  {
    "title": "#1 should works with online pages",
    "fullTitle": "macaca desktop sample--#1 should works with online pages",
    "duration": 20880,
    "state": "passed",
    "pass": true,
    "fail": false,
    "pending": false,
    "context": "\"../screenshots/86f2e889-e641-494e-a989-ab0ab44c69d3.png\"",
    "code": "const initialURL = 'https://www.baidu.com';\nreturn driver\n  .get(initialURL)\n  .sleep(3000)\n  .elementById('kw')\n  .sendKeys('macaca')\n  .sleep(3000)\n  .elementById('su')\n  .click()\n  .sleep(5000)\n  .source()\n  .then(function(html) {\n    html.should.containEql('macaca');\n  })\n  .hasElementByCss('#head > div.head_wrapper')\n  .then(function(hasHeadWrapper) {\n    hasHeadWrapper.should.be.true();\n  })\n  .elementByXPathOrNull('//*[@id=\"kw\"]')\n  .sendKeys(' elementByXPath')\n  .sleep(3000)\n  .elementById('su')\n  .click()\n  .sleep(5000)\n  .saveScreenshot('pic1');",
                            "uuid": "3ac3ba51-b26a-4fa6-9bd0-9fff568347ea",
    "skipped": false
  },
  {
    "title": "#2 should works with web",
    "fullTitle": "macaca desktop sample--#2 should works with web",
    "duration": 12791,
    "state": "passed",
    "pass": true,
    "fail": false,
    "pending": false,
    "context": "\"../screenshots/f752680b-3e7c-4eda-8eb9-1e4b4b5f96c3.png\"",
    "code": "const initialURL = 'https://www.baidu.com';\nreturn driver\n  .get(initialURL)\n  .sleep(3000)\n  .elementById('kw')\n  .sendKeys('Macaca')\n  .sleep(3000)\n  .elementById('su')\n  .click()\n  .sleep(5000)\n  .source()\n  .then(function(html) {\n    html.should.containEql('Macaca');\n  })\n  .saveScreenshot('pic2');",
                            "uuid": "0fadd3ca-8172-40a1-bf86-962d3a809bc8",
    "skipped": false
  },
  {
    "title": "#3 should works with iframe",
    "fullTitle": "macaca desktop sample--#3 should works with iframe",
    "duration": 6994,
    "state": "passed",
    "pass": true,
    "fail": false,
    "pending": false,
    "context": "\"../screenshots/2c2e1d9f-0adc-4ddb-9806-e6cc1705544a.png\"",
    "code": "const iframeURL = 'https://xudafeng.github.io/use-tinyMce-textEditor/';\nreturn driver\n  .get(iframeURL)\n  .sleep(3000)\n  .frame('mce_0_ifr')\n  .elementById('tinymce')\n  .sendKeys('这是一段测试')\n  .sleep(3000)\n  .takeScreenshot()\n  .then(imgData => {\n    const newImg = new Buffer(imgData, 'base64');\n    const screenshotFolder = path.resolve(__dirname, '../screenshot');\n    fs.writeFileSync(path.join(screenshotFolder, 'diff.png'), newImg.toString('binary'), 'binary')\n    const oldImgPath = path.join(screenshotFolder, 'origin.png');\n    const diffImgPath = path.join(screenshotFolder, 'diff.png');\n    return true || diffImage(oldImgPath, newImg, 0.1, diffImgPath);\n  })\n  .then(result => {\n    result.should.be.true();\n  })\n  .catch(e => {\n    console.log(e);\n  });",
                            "uuid": "5797160a-75e5-4ab8-a6d4-ab1291e2973e",
    "skipped": false
  }
],
  "pending": [],
  "_beforeEach": [],
  "_beforeAll": [],
  "_afterEach": [],
  "_afterAll": [
    {
      "title": "\"after all\" hook",
      "body": "() => {\n      return driver\n        .quit();\n    }",
      "async": 0,
      "sync": true,
      "_timeout": 300000,
      "_slow": 75,
      "_enableTimeouts": true,
      "timedOut": false,
      "_trace": {},
      "_retries": -1,
      "_currentRetry": 0,
      "pending": false,
      "type": "hook",
      "parent": "[Circular ~.suites.0.suites.0]",
      "ctx": {
        "_runnable": "[Circular ~.suites.0.suites.0._afterAll.0]",
        "test": "[Circular ~.suites.0.suites.0._afterAll.0]"
      },
      "_events": {},
      "_eventsCount": 1,
      "timer": {
        "0": null,
        "_called": false,
        "_idleTimeout": -1,
        "_idlePrev": null,
        "_idleNext": null,
        "_idleStart": 58337,
        "_onTimeout": null,
        "_repeat": null
      },
      "duration": 7,
      "_error": null
    }
  ],
  "root": false,
  "_timeout": 300000,
  "_enableTimeouts": true,
  "_slow": 75,
  "_retries": -1,
  "delayed": false,
  "parent": "[Circular ~.suites.0]",
  "file": "/macaca-test/desktop-browser-sample.test.js",
  "uuid": "529deb90-76b1-4962-995d-bf6797e84ce6",
  "fullFile": "macaca-test/desktop-browser-sample.test.js",
  "passes": [
    {
      "title": "#0 should be ok",
      "fullTitle": "macaca desktop sample--#0 should be ok",
      "duration": 7509,
      "state": "passed",
      "pass": true,
      "fail": false,
      "pending": false,
      "context": "\"../screenshots/34da7aaa-e94d-48be-a93a-70e851c952af.png\"",
      "code": "const url = path.join(__dirname, './pages/desktop-sample.html');\nreturn driver\n  .get(`file://${url}`)\n  .sleep(3000)\n  .execute(`document.querySelector('#select').selectedIndex = 1`)\n  .sleep(1000)\n  .elementById('select')\n  /*\n  .getProperty('value')\n  .then(value => {\n    value.should.be.equal('2');\n  })\n  */\n  .execute(`\n    var element = document.querySelector('#hover_text');\n    var event = document.createEvent('MouseEvent');\n    event.initMouseEvent('mouseover', true, true);\n    element.dispatchEvent(event);\n  `)\n  .elementById('hover_text')\n  .getComputedCss('color')\n  .then(value => {\n    value.should.containEql('255');\n  })\n  // https://github.com/macacajs/macaca-electron#windowalert\n  .execute(`\n    var e = document.createElement('div');\n    e.id = 'alert_msg';\n    window.alert = function() {\n      e.innerHTML = JSON.stringify(arguments[0]);\n      document.body.appendChild(e);\n    };\n  `)\n  .elementById('alert_button')\n  .click()\n  .elementById('alert_msg')\n  .text()\n  .then(value => {\n    value.should.containEql('this message is from alert');\n  })\n  .sleep(3000);",
                            "uuid": "03dacaa9-a969-4f88-bebd-5141fbe35cba",
      "skipped": false
    },
  {
    "title": "#1 should works with online pages",
    "fullTitle": "macaca desktop sample--#1 should works with online pages",
    "duration": 20880,
    "state": "passed",
    "pass": true,
    "fail": false,
    "pending": false,
    "context": "\"../screenshots/86f2e889-e641-494e-a989-ab0ab44c69d3.png\"",
    "code": "const initialURL = 'https://www.baidu.com';\nreturn driver\n  .get(initialURL)\n  .sleep(3000)\n  .elementById('kw')\n  .sendKeys('macaca')\n  .sleep(3000)\n  .elementById('su')\n  .click()\n  .sleep(5000)\n  .source()\n  .then(function(html) {\n    html.should.containEql('macaca');\n  })\n  .hasElementByCss('#head > div.head_wrapper')\n  .then(function(hasHeadWrapper) {\n    hasHeadWrapper.should.be.true();\n  })\n  .elementByXPathOrNull('//*[@id=\"kw\"]')\n  .sendKeys(' elementByXPath')\n  .sleep(3000)\n  .elementById('su')\n  .click()\n  .sleep(5000)\n  .saveScreenshot('pic1');",
                            "uuid": "3ac3ba51-b26a-4fa6-9bd0-9fff568347ea",
    "skipped": false
  },
  {
    "title": "#2 should works with web",
    "fullTitle": "macaca desktop sample--#2 should works with web",
    "duration": 12791,
    "state": "passed",
    "pass": true,
    "fail": false,
    "pending": false,
    "context": "\"../screenshots/f752680b-3e7c-4eda-8eb9-1e4b4b5f96c3.png\"",
    "code": "const initialURL = 'https://www.baidu.com';\nreturn driver\n  .get(initialURL)\n  .sleep(3000)\n  .elementById('kw')\n  .sendKeys('Macaca')\n  .sleep(3000)\n  .elementById('su')\n  .click()\n  .sleep(5000)\n  .source()\n  .then(function(html) {\n    html.should.containEql('Macaca');\n  })\n  .saveScreenshot('pic2');",
                            "uuid": "0fadd3ca-8172-40a1-bf86-962d3a809bc8",
    "skipped": false
  },
  {
    "title": "#3 should works with iframe",
    "fullTitle": "macaca desktop sample--#3 should works with iframe",
    "duration": 6994,
    "state": "passed",
    "pass": true,
    "fail": false,
    "pending": false,
    "context": "\"../screenshots/2c2e1d9f-0adc-4ddb-9806-e6cc1705544a.png\"",
    "code": "const iframeURL = 'https://xudafeng.github.io/use-tinyMce-textEditor/';\nreturn driver\n  .get(iframeURL)\n  .sleep(3000)\n  .frame('mce_0_ifr')\n  .elementById('tinymce')\n  .sendKeys('这是一段测试')\n  .sleep(3000)\n  .takeScreenshot()\n  .then(imgData => {\n    const newImg = new Buffer(imgData, 'base64');\n    const screenshotFolder = path.resolve(__dirname, '../screenshot');\n    fs.writeFileSync(path.join(screenshotFolder, 'diff.png'), newImg.toString('binary'), 'binary')\n    const oldImgPath = path.join(screenshotFolder, 'origin.png');\n    const diffImgPath = path.join(screenshotFolder, 'diff.png');\n    return true || diffImage(oldImgPath, newImg, 0.1, diffImgPath);\n  })\n  .then(result => {\n    result.should.be.true();\n  })\n  .catch(e => {\n    console.log(e);\n  });",
                            "uuid": "5797160a-75e5-4ab8-a6d4-ab1291e2973e",
    "skipped": false
  }
],
  "failures": [],
  "skipped": [],
  "totalTests": 4,
  "totalPasses": 4,
  "totalFailures": 0,
  "totalPending": 0,
  "totalSkipped": 0,
  "duration": 48174
}
],
  "tests": [],
  "pending": [],
  "_beforeEach": [],
  "_beforeAll": [
    {
      "title": "\"before all\" hook",
      "body": "() => {\n    return driver\n      .init({\n        platformName: 'desktop',\n        browserName: browser,\n        userAgent: `Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0 Safari/537.36 Macaca Custom UserAgent`,\n        deviceScaleFactor: 2\n      })\n      .setWindowSize(1280, 800);\n  }",
                    "async": 0,
  "sync": true,
  "_timeout": 300000,
  "_slow": 75,
  "_enableTimeouts": true,
  "timedOut": false,
  "_trace": {},
  "_retries": -1,
  "_currentRetry": 0,
  "pending": false,
  "type": "hook",
  "parent": "[Circular ~.suites.0]",
  "ctx": {
    "_runnable": {
      "title": "\"after all\" hook",
      "body": "function () {\n    opn(path.join(__dirname, '..', 'reports', 'index.html'));\n  }",
      "async": 0,
      "sync": true,
      "_timeout": 300000,
      "_slow": 75,
      "_enableTimeouts": true,
      "timedOut": false,
      "_trace": {},
      "_retries": -1,
      "_currentRetry": 0,
      "pending": false,
      "type": "hook",
      "parent": "[Circular ~.suites.0]",
      "ctx": "[Circular ~.suites.0._beforeAll.0.ctx]",
      "_events": {},
      "_eventsCount": 1,
      "duration": 4,
      "_error": null
    },
    "test": {
      "title": "\"after all\" hook",
      "body": "function () {\n    opn(path.join(__dirname, '..', 'reports', 'index.html'));\n  }",
      "async": 0,
      "sync": true,
      "_timeout": 300000,
      "_slow": 75,
      "_enableTimeouts": true,
      "timedOut": false,
      "_trace": {},
      "_retries": -1,
      "_currentRetry": 0,
      "pending": false,
      "type": "hook",
      "parent": "[Circular ~.suites.0]",
      "ctx": "[Circular ~.suites.0._beforeAll.0.ctx]",
      "_events": {},
      "_eventsCount": 1,
      "duration": 4,
      "_error": null
    }
  },
  "_events": {},
  "_eventsCount": 1,
  "timer": {
    "0": null,
    "_called": false,
    "_idleTimeout": -1,
    "_idlePrev": null,
    "_idleNext": null,
    "_idleStart": 818,
    "_onTimeout": null,
    "_repeat": null
  },
  "duration": 3254,
  "_error": null
}
],
  "_afterEach": [
    {
      "title": "\"after each\" hook",
      "body": "function () {\n    return driver\n      .customSaveScreenshot(this)\n      .sleep(1000)\n  }",
      "async": 0,
      "sync": true,
      "_timeout": 300000,
      "_slow": 75,
      "_enableTimeouts": true,
      "timedOut": false,
      "_trace": {},
      "_retries": -1,
      "_currentRetry": 0,
      "pending": false,
      "type": "hook",
      "parent": "[Circular ~.suites.0]",
      "ctx": {
        "_runnable": {
          "title": "\"after all\" hook",
          "body": "function () {\n    opn(path.join(__dirname, '..', 'reports', 'index.html'));\n  }",
          "async": 0,
          "sync": true,
          "_timeout": 300000,
          "_slow": 75,
          "_enableTimeouts": true,
          "timedOut": false,
          "_trace": {},
          "_retries": -1,
          "_currentRetry": 0,
          "pending": false,
          "type": "hook",
          "parent": "[Circular ~.suites.0]",
          "ctx": "[Circular ~.suites.0._afterEach.0.ctx]",
          "_events": {},
          "_eventsCount": 1,
          "duration": 4,
          "_error": null
        },
        "test": {
          "title": "\"after all\" hook",
          "body": "function () {\n    opn(path.join(__dirname, '..', 'reports', 'index.html'));\n  }",
          "async": 0,
          "sync": true,
          "_timeout": 300000,
          "_slow": 75,
          "_enableTimeouts": true,
          "timedOut": false,
          "_trace": {},
          "_retries": -1,
          "_currentRetry": 0,
          "pending": false,
          "type": "hook",
          "parent": "[Circular ~.suites.0]",
          "ctx": "[Circular ~.suites.0._afterEach.0.ctx]",
          "_events": {},
          "_eventsCount": 1,
          "duration": 4,
          "_error": null
        }
      },
      "_events": {},
      "_eventsCount": 1,
      "timer": {
        "0": null,
        "_called": false,
        "_idleTimeout": -1,
        "_idlePrev": null,
        "_idleNext": null,
        "_idleStart": 57014,
        "_onTimeout": null,
        "_repeat": null
      },
      "duration": 1325,
      "_error": null
    }
  ],
  "_afterAll": [
    {
      "title": "\"after all\" hook",
      "body": "function () {\n    opn(path.join(__dirname, '..', 'reports', 'index.html'));\n  }",
      "async": 0,
      "sync": true,
      "_timeout": 300000,
      "_slow": 75,
      "_enableTimeouts": true,
      "timedOut": false,
      "_trace": {},
      "_retries": -1,
      "_currentRetry": 0,
      "pending": false,
      "type": "hook",
      "parent": "[Circular ~.suites.0]",
      "ctx": {
        "_runnable": "[Circular ~.suites.0._afterAll.0]",
        "test": "[Circular ~.suites.0._afterAll.0]"
      },
      "_events": {},
      "_eventsCount": 1,
      "duration": 4,
      "_error": null
    }
  ],
  "root": false,
  "_timeout": 300000,
  "_enableTimeouts": true,
  "_slow": 75,
  "_retries": -1,
  "delayed": false,
  "parent": "[Circular ~]",
  "file": "/macaca-test/desktop-browser-sample.test.js",
  "uuid": "6284a170-c7a4-48ac-8d4a-801d717a5bbc",
  "fullFile": "macaca-test/desktop-browser-sample.test.js",
  "passes": [],
  "failures": [],
  "skipped": [],
  "totalTests": 0,
  "totalPasses": 0,
  "totalFailures": 0,
  "totalPending": 0,
  "totalSkipped": 0,
  "duration": 0
}
],
  "tests": [],
  "pending": [],
  "_beforeEach": [],
  "_beforeAll": [],
  "_afterEach": [],
  "_afterAll": [],
  "root": true,
  "_timeout": 2000,
  "_enableTimeouts": true,
  "_slow": 75,
  "_retries": -1,
  "delayed": false,
  "_events": {
    "pre-require": [
      null,
      null,
      null,
      null
    ]
  },
  "_eventsCount": 1,
  "uuid": "590ecd0d-f1c8-4d26-b06d-3d9909f38541",
  "fullFile": "",
  "file": "",
  "passes": [],
  "failures": [],
  "skipped": [],
  "totalTests": 0,
  "totalPasses": 0,
  "totalFailures": 0,
  "totalPending": 0,
  "totalSkipped": 0,
  "duration": 0,
  "_totalTime": 48174
};
